#############################
##
##  File:
##      \file makefile
##
##  Description:
##      \brief Example-level makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

default:
	#$(MAKE) -C example-1

clean:
	#$(MAKE) -C example-1 clean
