language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev doxygen gsl-bin libgsl0-dev google-mock cmake libgtest-dev
before_script:
  - cd /usr/src/gtest; sudo cmake CMakeLists.txt; sudo make; sudo cp *.a /usr/lib; cd -
script: make && make test && make run-test
notifications:
  recipients:
    - caleb@calebwherry.com
    - robertofrances@gmail.com
  email:
    on_success: change
    on_failure: always
