language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-dev
script: make && make test
notifications:
  recipients:
    - caleb@calebwherry.com
    - robertofrances@gmail.com
  email:
    on_success: change
    on_failure: always
