.TH "lib/DataStructures Directory Reference" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DataStructures Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBinaryTree\&.hpp\fP"
.br
.ti -1c
.RI "file \fBDoublyLinkedList\&.hpp\fP"
.br
.ti -1c
.RI "file \fBMatrix\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSinglyLinkedList\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTree\&.hpp\fP"
.br
.in -1c
