.TH "binaryTree::Node< T >" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binaryTree::Node< T > \- 
.PP
Binary Tree \fBNode\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'BinaryTree\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBdatum\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBleftChild\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBrightChild\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct binaryTree::Node< T >"
Binary Tree \fBNode\fP\&. 
.PP
Definition at line 36 of file BinaryTree\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBbinaryTree::Node\fP< T >::\fBNode\fP ()\fC [inline]\fP"

.PP
Definition at line 38 of file BinaryTree\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> T \fBbinaryTree::Node\fP< T >::datum"

.PP
Definition at line 44 of file BinaryTree\&.hpp\&.
.PP
Referenced by binaryTree::BinaryTree< T >::inOrderTraversal(), binaryTree::BinaryTree< T >::insert(), binaryTree::BinaryTree< T >::postOrderTraversal(), and binaryTree::BinaryTree< T >::preOrderTraversal()\&.
.SS "template<typename T> \fBNode\fP* \fBbinaryTree::Node\fP< T >::leftChild"

.PP
Definition at line 45 of file BinaryTree\&.hpp\&.
.PP
Referenced by binaryTree::BinaryTree< T >::inOrderTraversal(), binaryTree::BinaryTree< T >::insert(), binaryTree::BinaryTree< T >::postOrderTraversal(), and binaryTree::BinaryTree< T >::preOrderTraversal()\&.
.SS "template<typename T> \fBNode\fP* \fBbinaryTree::Node\fP< T >::rightChild"

.PP
Definition at line 46 of file BinaryTree\&.hpp\&.
.PP
Referenced by binaryTree::BinaryTree< T >::inOrderTraversal(), binaryTree::BinaryTree< T >::insert(), binaryTree::BinaryTree< T >::postOrderTraversal(), and binaryTree::BinaryTree< T >::preOrderTraversal()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
