.TH "lib/DataStructures/BinaryTree.hpp" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/DataStructures/BinaryTree.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Tree\&.hpp'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBbinaryTree::Node< T >\fP"
.br
.RI "\fIBinary Tree \fBNode\fP\&. \fP"
.ti -1c
.RI "class \fBbinaryTree::BinaryTree< T >\fP"
.br
.RI "\fIBinary Tree class\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBbinaryTree\fP"
.br
.RI "\fI\fBbinaryTree\fP Namespace \fP"
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBbinaryTree\fP"
.br
.RI "\fI\fBbinaryTree\fP Namespace \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
