.TH "binaryTree" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binaryTree \- 
.PP
\fBbinaryTree\fP Namespace  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNode\fP"
.br
.RI "\fIBinary Tree \fBNode\fP\&. \fP"
.ti -1c
.RI "class \fBBinaryTree\fP"
.br
.RI "\fIBinary Tree class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBbinaryTree\fP Namespace 
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
