.TH "BogoSort< T >" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BogoSort< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'BogoSort\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBogoSort\fP ()"
.br
.ti -1c
.RI "\fBBogoSort\fP (std::vector< T > inList)"
.br
.ti -1c
.RI "int \fBsort\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< T > \fBlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>class BogoSort< T >"

.PP
Definition at line 31 of file BogoSort\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBBogoSort\fP< T >::\fBBogoSort\fP ()"

.PP
Definition at line 47 of file BogoSort\&.hpp\&.
.SS "template<typename T > \fBBogoSort\fP< T >::\fBBogoSort\fP (std::vector< T >inList)"

.PP
Definition at line 53 of file BogoSort\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBBogoSort\fP< T >::print ()"

.PP
Definition at line 76 of file BogoSort\&.hpp\&.
.SS "template<typename T > int \fBBogoSort\fP< T >::sort ()"

.PP
Definition at line 59 of file BogoSort\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T > std::vector<T> \fBBogoSort\fP< T >::list\fC [private]\fP"

.PP
Definition at line 34 of file BogoSort\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
