.TH "lib/Sorting/BogoSort.hpp" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/Sorting/BogoSort.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBogoSort< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
