.TH "doublyLinkedList::Node< T >" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doublyLinkedList::Node< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'DoublyLinkedList\&.hpp'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBdatum\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBprev\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct doublyLinkedList::Node< T >"

.PP
Definition at line 33 of file DoublyLinkedList\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> T \fBdoublyLinkedList::Node\fP< T >::datum"

.PP
Definition at line 34 of file DoublyLinkedList\&.hpp\&.
.PP
Referenced by doublyLinkedList::DoublyLinkedList< T >::popBack(), doublyLinkedList::DoublyLinkedList< T >::print(), and doublyLinkedList::DoublyLinkedList< T >::pushBack()\&.
.SS "template<typename T> \fBNode\fP* \fBdoublyLinkedList::Node\fP< T >::next"

.PP
Definition at line 36 of file DoublyLinkedList\&.hpp\&.
.PP
Referenced by doublyLinkedList::DoublyLinkedList< T >::print(), and doublyLinkedList::DoublyLinkedList< T >::pushBack()\&.
.SS "template<typename T> \fBNode\fP* \fBdoublyLinkedList::Node\fP< T >::prev"

.PP
Definition at line 35 of file DoublyLinkedList\&.hpp\&.
.PP
Referenced by doublyLinkedList::DoublyLinkedList< T >::pushBack()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
