.TH "matrix" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix \- 
.PP
matrix Namespace  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.RI "\fI\fBMatrix\fP class\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBMatrix\fP< T > &rhs)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::string \fBemptyStr\fP = std::string()"
.br
.RI "\fIEmpty string used for default pad in matrix printing\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
matrix Namespace 
.SH "Function Documentation"
.PP 
.SS "template<typename T > std::ostream& matrix::operator<< (std::ostream &os, const Matrix< T > &rhs)"
Display 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP Output stream 
.br
\fIrhs\fP \fBMatrix\fP to output 
.RE
.PP

.PP
Definition at line 302 of file Matrix\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "const std::string matrix::emptyStr = std::string()"

.PP
Empty string used for default pad in matrix printing\&. 
.PP
Definition at line 37 of file Matrix\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
