.TH "searchUtil" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
searchUtil \- 
.PP
\fBsearchUtil\fP Namespace  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBexists\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBsearchUtil\fP Namespace 
.SH "Function Documentation"
.PP 
.SS "bool searchUtil::exists ()"

.PP
Definition at line 27 of file SearchUtil\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
