.TH "singlyLinkedList::SinglyLinkedList< T >" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
singlyLinkedList::SinglyLinkedList< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'SinglyLinkedList\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSinglyLinkedList\fP ()"
.br
.ti -1c
.RI "void \fBinsert\fP (T data)"
.br
.ti -1c
.RI "void \fBremove\fP (T data)"
.br
.ti -1c
.RI "bool \fBcontains\fP (T data)"
.br
.ti -1c
.RI "void \fBpushBack\fP (T data)"
.br
.ti -1c
.RI "void \fBpushFront\fP (T data)"
.br
.ti -1c
.RI "void \fBpopBack\fP ()"
.br
.ti -1c
.RI "void \fBpopFront\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "void \fBprintReverse\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP< T > * \fBhead\fP"
.br
.ti -1c
.RI "\fBNode\fP< T > * \fBtail\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>class singlyLinkedList::SinglyLinkedList< T >"

.PP
Definition at line 39 of file SinglyLinkedList\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBsinglyLinkedList::SinglyLinkedList\fP< T >::\fBSinglyLinkedList\fP ()"

.PP
Definition at line 70 of file SinglyLinkedList\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > bool \fBsinglyLinkedList::SinglyLinkedList\fP< T >::contains (Tdata)"

.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::insert (Tdata)"

.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::popBack ()"

.PP
Definition at line 109 of file SinglyLinkedList\&.hpp\&.
.PP
References singlyLinkedList::Node< T >::next\&.
.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::popFront ()"

.PP
Definition at line 123 of file SinglyLinkedList\&.hpp\&.
.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::print ()"

.PP
Definition at line 129 of file SinglyLinkedList\&.hpp\&.
.PP
References singlyLinkedList::Node< T >::datum, and singlyLinkedList::Node< T >::next\&.
.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::printReverse ()"

.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::pushBack (Tdata)"

.PP
Definition at line 78 of file SinglyLinkedList\&.hpp\&.
.PP
References singlyLinkedList::Node< T >::datum, and singlyLinkedList::Node< T >::next\&.
.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::pushFront (Tdata)"

.PP
Definition at line 103 of file SinglyLinkedList\&.hpp\&.
.SS "template<typename T > void \fBsinglyLinkedList::SinglyLinkedList\fP< T >::remove (Tdata)"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > \fBNode\fP<T>* \fBsinglyLinkedList::SinglyLinkedList\fP< T >::head\fC [private]\fP"

.PP
Definition at line 42 of file SinglyLinkedList\&.hpp\&.
.SS "template<typename T > int \fBsinglyLinkedList::SinglyLinkedList\fP< T >::size\fC [private]\fP"

.PP
Definition at line 44 of file SinglyLinkedList\&.hpp\&.
.SS "template<typename T > \fBNode\fP<T>* \fBsinglyLinkedList::SinglyLinkedList\fP< T >::tail\fC [private]\fP"

.PP
Definition at line 43 of file SinglyLinkedList\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
