.TH "singlyLinkedList::Node< T >" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
singlyLinkedList::Node< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'SinglyLinkedList\&.hpp'\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBdatum\fP"
.br
.ti -1c
.RI "\fBNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>struct singlyLinkedList::Node< T >"

.PP
Definition at line 33 of file SinglyLinkedList\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T> T \fBsinglyLinkedList::Node\fP< T >::datum"

.PP
Definition at line 34 of file SinglyLinkedList\&.hpp\&.
.PP
Referenced by singlyLinkedList::SinglyLinkedList< T >::print(), and singlyLinkedList::SinglyLinkedList< T >::pushBack()\&.
.SS "template<typename T> \fBNode\fP* \fBsinglyLinkedList::Node\fP< T >::next"

.PP
Definition at line 35 of file SinglyLinkedList\&.hpp\&.
.PP
Referenced by singlyLinkedList::SinglyLinkedList< T >::popBack(), singlyLinkedList::SinglyLinkedList< T >::print(), and singlyLinkedList::SinglyLinkedList< T >::pushBack()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
