.TH "lib/StringUtil/StringUtil.h" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/StringUtil/StringUtil.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBstringUtil\fP"
.br
.RI "\fI\fBstringUtil\fP Namespace \fP"
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBstringUtil\fP"
.br
.RI "\fI\fBstringUtil\fP Namespace \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > std::string \fBstringUtil::toString\fP (T inVar)"
.br
.RI "\fIPrints any type to string\&. \fP"
.ti -1c
.RI "int \fBstringUtil::length\fP (const std::string &inStr)"
.br
.RI "\fIReturns length of a string\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
