.TH "stringUtil" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stringUtil \- 
.PP
\fBstringUtil\fP Namespace  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBlength\fP (const std::string &inStr)"
.br
.RI "\fIReturns length of a string\&. \fP"
.ti -1c
.RI "template<typename T > std::string \fBtoString\fP (T inVar)"
.br
.RI "\fIPrints any type to string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBstringUtil\fP Namespace 
.SH "Function Documentation"
.PP 
.SS "int stringUtil::length (const std::string &inStr)"

.PP
Returns length of a string\&. 
.PP
Definition at line 28 of file StringUtil\&.cpp\&.
.SS "template<typename T > std::string stringUtil::toString (TinVar)"

.PP
Prints any type to string\&. 
.PP
Definition at line 33 of file StringUtil\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
