.TH "tree" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree \- 
.PP
Namespace:  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTree\fP"
.br
.RI "\fI\fBTree\fP Class: \fP"
.in -1c
.SH "Detailed Description"
.PP 
Namespace: 
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
