.TH "tree::Tree" 3 "Thu Jan 16 2014" "C++ Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tree::Tree \- 
.PP
\fBTree\fP Class:  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'Tree\&.hpp'\fP
.PP
Inherited by \fBbinaryTree::BinaryTree< T >\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTree\fP ()"
.br
.RI "\fIDefault Constructor: \fP"
.ti -1c
.RI "\fB~Tree\fP ()"
.br
.RI "\fIDeconstructor: \fP"
.ti -1c
.RI "virtual void \fBprint\fP ()=0"
.br
.RI "\fIPure virtual Print: \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBdepth\fP"
.br
.RI "\fI\fBTree\fP Depth\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBTree\fP Class: 
.PP
Definition at line 32 of file Tree\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tree::Tree::Tree ()\fC [protected]\fP"

.PP
Default Constructor: 
.PP
Definition at line 50 of file Tree\&.hpp\&.
.SS "tree::Tree::~Tree ()\fC [protected]\fP"

.PP
Deconstructor: 
.PP
Definition at line 55 of file Tree\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void tree::Tree::print ()\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Pure virtual Print: 
.PP
Implemented in \fBbinaryTree::BinaryTree< T >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int tree::Tree::depth\fC [protected]\fP"

.PP
\fBTree\fP Depth\&. 
.PP
Definition at line 46 of file Tree\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Libraries from the source code\&.
