#############################
##
##  File:
##      \file Makefile
##
##  Description:
##      \brief Sorting tests makefile for C++ Libraries
##
##  Author:
##      \author J. Caleb Wherry
##
#############################

ROOT = $(abspath ../../..)
SRCS = $(wildcard *.cpp)
PROGS = $(SRCS:%.cpp=%)
INCLUDES += -I${ROOT}/lib/Sorting
LIBS +=

include $(abspath ../Makefile-test.common)
