C++ Libraries: matrix::Matrix< T > Class Template Reference
matrix::Matrix< T > Class Template Reference
Matrix class.
#include "Matrix.hpp"
Public Member Functions
Matrix ()
Default Constructor.
Matrix (const Matrix< T > &rhs)
Copy Constructor.
Matrix (uint32_t _numRows, uint32_t _numCols, const T &initVals=0, const std::string &_pad=emptyStr)
Custom Constructor.
Matrix (std::initializer_list< std::initializer_list< T >> _matrix)
Initializer_list Constructor.
~Matrix ()
Deconstructor.
std::vector< std::vector< T > > getMatrix () const
Matrix Accessor.
uint32_t getNumRows () const
uint32_t getNumCols () const
Row accessor.
std::string getPad () const
Columns accessor.
void setPad (const std::string &_pad)
Pad accessor.
Matrix< T > & operator= (const Matrix< T > &rhs)
Assignment.
Matrix< T > operator* (const Matrix< T > &rhs) const
Matrix/Matrix Multiplication.
Matrix< T > operator+ (const Matrix< T > &rhs) const
Matrix/Matrix Addition.
Matrix< T > operator- (const Matrix< T > &rhs) const
Matrix/Matrix Subtraction.
Matrix< T > operator* (const T &rhs) const
Matrix/Scalar Multiplication.
Matrix< T > operator/ (const T &rhs) const
Matrix/Scalar Division.
Matrix< T > operator+ (const T &rhs) const
Matrix/Scalar Addition.
Matrix< T > operator- (const T &rhs) const
Matrix/Scalar Subtraction.
Matrix< T > operator- () const
Matrix Negative.
Matrix< T > operator^ (const uint32_t &power) const
Matrix Power function.
T & operator() (const uint32_t &row, const uint32_t &col)
Matrix Element Access.
const T & operator() (const uint32_t &row, const uint32_t &col) const
Matrix Element Access (const)
bool operator== (const Matrix< T > &rhs) const
Matrix Comparison.
Matrix< T > transpose () const
Matrix Transpose.
Matrix< T > complexConjugate () const
Matrix Complex Conjugate.
Matrix< T > conjugateTranspose () const
Matrix Complex Conjugate Transpose.
Matrix< T > identity () const
Identity matrix of same size and type.
bool isSquare () const
Is matrix square?
bool isReal () const
Are all elements real?
bool isComplex () const
Do any elements have imaginary parts?
bool isSymmetric () const
A = A^T ?
bool isSkewSymmetric () const
-A = A^T ?
bool isHermitian () const
A = A^dagger (Complex extension of isSymmetric()) ?
bool isSelfAdjoint () const
Same as isHermitian()
bool isSkewHermitian () const
-A = A^dagger (Complex extension of isSkewSymmetric())
bool isNormal () const
Real: A*A^T = A^T*A; Complex: A*A^dagger = A^dagger*A.
bool isOrthogonal () const
A*A^T = A^T*A = I.
bool isUnitary () const
A*A^dagger = A^dagger*A = I (Complex extension of isOrthogonal())
bool isProjection () const
A = A^2.
bool isIdentity () const
A = I.
bool commutesWith (const Matrix< T > &rhs) const
T trace () const
Sum of diagonal elements.
T sum () const
Sum of all elements.
Private Attributes
std::vector< std::vector< T > > matrix
Matrix.
uint32_t numRows
Number of rows.
uint32_t numCols
Number of columns.
std::string pad
Pad used when printing matrix.
Friends
template<typename U >
std::ostream & operator<< (std::ostream &os, const Matrix< T > &rhs)
Pad modifier.
Detailed Description
template<typename T>
class matrix::Matrix< T >
Matrix class.
Definition at line 41 of file Matrix.hpp.
Constructor & Destructor Documentation
template<typename T > matrix::Matrix< T >::Matrix ()
Default Constructor.
Definition at line 214 of file Matrix.hpp.
References matrix::Matrix< T >::matrix.
template<typename T > matrix::Matrix< T >::Matrix (const Matrix< T > & rhs)
Copy Constructor.
Parameters
rhs Matrix to copy from.
Definition at line 226 of file Matrix.hpp.
References matrix::Matrix< T >::getMatrix(), matrix::Matrix< T >::getNumCols(), matrix::Matrix< T >::getNumRows(), and matrix::Matrix< T >::getPad().
template<typename T > matrix::Matrix< T >::Matrix (uint32_t _numRows, uint32_t _numCols, const T & initVals = 0, const std::string & _pad = emptyStr)
Custom Constructor.
Parameters
_numRows Number of rows new matrix will have.
_numCols Number of columns new matrix will have.
initVals Initial value of all elements of new matrix.
_pad Printing pad.
Definition at line 237 of file Matrix.hpp.
References matrix::Matrix< T >::matrix, matrix::Matrix< T >::numCols, and matrix::Matrix< T >::numRows.
template<typename T > matrix::Matrix< T >::Matrix (std::initializer_list< std::initializer_list< T >> _matrix)
Initializer_list Constructor.
Parameters
_matrix Initial values list.
Definition at line 258 of file Matrix.hpp.
References matrix::Matrix< T >::matrix, matrix::Matrix< T >::numCols, and matrix::Matrix< T >::numRows.
template<typename T > matrix::Matrix< T >::~Matrix ()
Deconstructor.
Definition at line 295 of file Matrix.hpp.
Member Function Documentation
template<typename T > bool matrix::Matrix< T >::commutesWith (const Matrix< T > & rhs) const
Definition at line 896 of file Matrix.hpp.
References matrix::Matrix< T >::getNumCols(), and matrix::Matrix< T >::getNumRows().
template<typename T > Matrix< T > matrix::Matrix< T >::complexConjugate () const
Matrix Complex Conjugate.
Definition at line 623 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::conjugateTranspose().
template<typename T > Matrix< T > matrix::Matrix< T >::conjugateTranspose () const
Matrix Complex Conjugate Transpose.
Definition at line 651 of file Matrix.hpp.
References matrix::Matrix< T >::complexConjugate(), matrix::Matrix< T >::isReal(), and matrix::Matrix< T >::transpose().
template<typename T> std::vector<std::vector<T> > matrix::Matrix< T >::getMatrix () const inline
Matrix Accessor.
Definition at line 87 of file Matrix.hpp.
References matrix::Matrix< T >::matrix.
Referenced by matrix::Matrix< T >::Matrix().
template<typename T> uint32_t matrix::Matrix< T >::getNumCols () const inline
Row accessor.
Definition at line 91 of file Matrix.hpp.
References matrix::Matrix< T >::numCols.
Referenced by matrix::Matrix< T >::commutesWith(), matrix::Matrix< T >::Matrix(), matrix::Matrix< T >::operator*(), matrix::Matrix< T >::operator+(), matrix::Matrix< T >::operator-(), matrix::Matrix< T >::operator=(), and matrix::Matrix< T >::operator==().
template<typename T> uint32_t matrix::Matrix< T >::getNumRows () const inline
Definition at line 90 of file Matrix.hpp.
References matrix::Matrix< T >::numRows.
Referenced by matrix::Matrix< T >::commutesWith(), matrix::Matrix< T >::Matrix(), matrix::Matrix< T >::operator*(), matrix::Matrix< T >::operator+(), matrix::Matrix< T >::operator-(), matrix::Matrix< T >::operator=(), and matrix::Matrix< T >::operator==().
template<typename T> std::string matrix::Matrix< T >::getPad () const inline
Columns accessor.
Definition at line 94 of file Matrix.hpp.
References matrix::Matrix< T >::pad.
Referenced by matrix::Matrix< T >::Matrix(), and matrix::Matrix< T >::operator=().
template<typename T > Matrix< T > matrix::Matrix< T >::identity () const
Identity matrix of same size and type.
Definition at line 665 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isComplex () const
Do any elements have imaginary parts?
Definition at line 711 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isHermitian () const
A = A^dagger (Complex extension of isSymmetric()) ?
Definition at line 748 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isIdentity () const
A = I.
Definition at line 875 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isNormal () const
Real: A*A^T = A^T*A; Complex: A*A^dagger = A^dagger*A.
Definition at line 785 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isOrthogonal () const
A*A^T = A^T*A = I.
Definition at line 808 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isProjection () const
A = A^2.
Definition at line 854 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isReal () const
Are all elements real?
Definition at line 689 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::conjugateTranspose().
template<typename T > bool matrix::Matrix< T >::isSelfAdjoint () const
Same as isHermitian()
Definition at line 762 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isSkewHermitian () const
-A = A^dagger (Complex extension of isSkewSymmetric())
Definition at line 769 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isSkewSymmetric () const
-A = A^T ?
Definition at line 734 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isSquare () const
Is matrix square?
Definition at line 682 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isSymmetric () const
A = A^T ?
Definition at line 720 of file Matrix.hpp.
template<typename T > bool matrix::Matrix< T >::isUnitary () const
A*A^dagger = A^dagger*A = I (Complex extension of isOrthogonal())
Definition at line 831 of file Matrix.hpp.
template<typename T > T & matrix::Matrix< T >::operator() (const uint32_t & row, const uint32_t & col)
Matrix Element Access.
Definition at line 536 of file Matrix.hpp.
template<typename T > const T & matrix::Matrix< T >::operator() (const uint32_t & row, const uint32_t & col) const
Matrix Element Access (const)
Definition at line 551 of file Matrix.hpp.
template<typename T > Matrix< T > matrix::Matrix< T >::operator* (const Matrix< T > & rhs) const
Matrix/Matrix Multiplication.
Definition at line 365 of file Matrix.hpp.
References matrix::Matrix< T >::getNumCols(), and matrix::Matrix< T >::getNumRows().
template<typename T > Matrix< T > matrix::Matrix< T >::operator* (const T & rhs) const
Matrix/Scalar Multiplication.
Definition at line 441 of file Matrix.hpp.
template<typename T > Matrix< T > matrix::Matrix< T >::operator+ (const Matrix< T > & rhs) const
Matrix/Matrix Addition.
Definition at line 397 of file Matrix.hpp.
References matrix::Matrix< T >::getNumCols(), and matrix::Matrix< T >::getNumRows().
template<typename T > Matrix< T > matrix::Matrix< T >::operator+ (const T & rhs) const
Matrix/Scalar Addition.
Definition at line 483 of file Matrix.hpp.
template<typename T > Matrix< T > matrix::Matrix< T >::operator- (const Matrix< T > & rhs) const
Matrix/Matrix Subtraction.
Definition at line 425 of file Matrix.hpp.
References matrix::Matrix< T >::getNumCols(), and matrix::Matrix< T >::getNumRows().
template<typename T > Matrix< T > matrix::Matrix< T >::operator- (const T & rhs) const
Matrix/Scalar Subtraction.
Definition at line 501 of file Matrix.hpp.
template<typename T > Matrix< T > matrix::Matrix< T >::operator- () const
Matrix Negative.
Definition at line 508 of file Matrix.hpp.
template<typename T > Matrix< T > matrix::Matrix< T >::operator/ (const T & rhs) const
Matrix/Scalar Division.
Definition at line 459 of file Matrix.hpp.
template<typename T > Matrix< T > & matrix::Matrix< T >::operator= (const Matrix< T > & rhs)
Assignment.
Parameters
rhs Matrix to assign
Definition at line 327 of file Matrix.hpp.
References matrix::Matrix< T >::getNumCols(), matrix::Matrix< T >::getNumRows(), and matrix::Matrix< T >::getPad().
template<typename T > bool matrix::Matrix< T >::operator== (const Matrix< T > & rhs) const
Matrix Comparison.
Definition at line 566 of file Matrix.hpp.
References matrix::Matrix< T >::getNumCols(), and matrix::Matrix< T >::getNumRows().
template<typename T > Matrix< T > matrix::Matrix< T >::operator^ (const uint32_t & power) const
Matrix Power function.
Definition at line 515 of file Matrix.hpp.
template<typename T> void matrix::Matrix< T >::setPad (const std::string & _pad) inline
Pad accessor.
Definition at line 95 of file Matrix.hpp.
References matrix::Matrix< T >::pad.
template<typename T > T matrix::Matrix< T >::sum () const
Sum of all elements.
Definition at line 934 of file Matrix.hpp.
template<typename T > T matrix::Matrix< T >::trace () const
Sum of diagonal elements.
Definition at line 918 of file Matrix.hpp.
template<typename T > Matrix< T > matrix::Matrix< T >::transpose () const
Matrix Transpose.
Definition at line 593 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::conjugateTranspose().
Friends And Related Function Documentation
template<typename T> template<typename U > std::ostream& operator<< (std::ostream & os, const Matrix< T > & rhs) friend
Pad modifier.
Display
Parameters
os Output stream
rhs Matrix to output
Definition at line 302 of file Matrix.hpp.
Member Data Documentation
template<typename T> std::vector<std::vector<T> > matrix::Matrix< T >::matrix private
Matrix.
Definition at line 45 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::getMatrix(), and matrix::Matrix< T >::Matrix().
template<typename T> uint32_t matrix::Matrix< T >::numCols private
Number of columns.
Definition at line 47 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::getNumCols(), and matrix::Matrix< T >::Matrix().
template<typename T> uint32_t matrix::Matrix< T >::numRows private
Number of rows.
Definition at line 46 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::getNumRows(), and matrix::Matrix< T >::Matrix().
template<typename T> std::string matrix::Matrix< T >::pad private
Pad used when printing matrix.
Definition at line 48 of file Matrix.hpp.
Referenced by matrix::Matrix< T >::getPad(), and matrix::Matrix< T >::setPad().
The documentation for this class was generated from the following file:
lib/DataStructures/Matrix.hpp